### ISSUE TITLE
Cannot access conversations

### ISSUE THREAD

**Issue by sensiblepuffin** [gsurrel/MessengerBypasser#2]
I am able to access my inbox and compose new messages without seeing any sort of popup from Tinfoil, but as soon as I click on a conversation a 'webpage not available' message appears - perhaps an intent that is not being caught?

The URL it tries to load: intent://groupthreadfbid/$myfacebookID$/?show_multiaccount=true#Intent;scheme=fb-messenger;package=com.facebook.orca;end.

**Comment by gsurrel** [comment]
It's indeed a known bug but because of Tinfoil for Facebook: it tries to open the intent in its own webview instead of sending it to the system for opening it when opening a group conversation. In the end, nothing leaves Tinfoil so I can't intercept it (as far as I know).

The only thing I have found is just to press the "back" button when I'm opening a group conversation: it displays the conversation properly (at the cost of one full page reload). Not ideal but it somehow works for now.
